### ISSUE TITLE
Version of samtools used?

### ISSUE THREAD

**Issue by hengjwj** [y9c/m5C-UBSseq#5]
Hi, I tried running the pipeline and got this error:

Killed
(ERR): hisat2-align exited with value 137
[E::aux_parse] Incomplete aux field
samtools view: error reading file "-"
samtools view: error closing "-": -5

Sounds like the error stemmed from samtools. I used 1.21 when I got this error. Which version did you use?

**Comment by y9c** [comment]
Hi, thank you for your interset in this project. Any version of samtools should works. This error message do not have enough information for debugging. Please update your config file and test fastq file. This can help me reproduce this issue.

**Comment by hengjwj** [comment]
Hi,

I tried running the pipeline on the single-end datasets SRR23538287 and SRR23538288 from the paper (SRR23538289 gave some error as follows: "Sequence descriptions don't match ('SRR23538289.152141938 152141938 length=121' != 'SRR23538289.152141938 1u2141938 length=121').").

This time, the error was unrelated to samtools.

my config file looks like:

```
# tools and scripts
path:
  samtools: /home/DDL/miniconda3/envs/sam/bin/samtools
  hisat3n: /mnt/d/Joel/bin/hisat-3n/hisat-3n
  hisat3ntable: /mnt/d/Joel/bin/hisat-3n/hisat-3n-table
  join_pileup.py: /mnt/d/Joel/UBS-seq/m5C-UBSseq/bin/join_pileup.py
  group_pileup.py: /mnt/d/Joel/UBS-seq/m5C-UBSseq/bin/group_pileup.py
  select_sites.py: /mnt/d/Joel/UBS-seq/m5C-UBSseq/bin/select_sites.py
  filter_sites.py: /mnt/d/Joel/UBS-seq/m5C-UBSseq/bin/filter_sites.py

library: INLINE
makedup: false

# reference genome and index
reference:
  contamination:
    fa: /mnt/d/Joel/GRCh38.112_ensembl/Homo_sapiens.GRCh38.rRNA.tRNA.fa
    hisat3n: /mnt/d/Joel/GRCh38.112_ensembl/index/hisat3n/contamination/rRNA_tRNA
  genes:
    fa: /mnt/d/Joel/GRCh38.112_ensembl/Homo_sapiens.GRCh38.cdna.all.fa
    hisat3n: /mnt/d/Joel/GRCh38.112_ensembl/index/hisat3n/Homo_sapiens.GRCh38.cdna.all
  genome:
    fa: /mnt/d/Joel/GRCh38.112_ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    hisat3n: /mnt/d/Joel/GRCh38.112_ensembl/index/hisat3n/Homo_sapiens.GRCh38.dna.primary_assembly

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  HEK293T-WT1:
    data:
      - R1: /mnt/d/Joel/UBS-seq/hek293t/SRR23538287/SRR23538287_direct.fastq.gz
    group: WT
  HEK293T-WT2:
    data:
      - R1: /mnt/d/Joel/UBS-seq/hek293t/SRR23538288/SRR23538288_direct.fastq.gz
    group: WT
```



Subsequently, I got these messages:

```
localrule cutadapt_SE:
    input: /mnt/d/Joel/UBS-seq/hek293t/SRR23538287/SRR23538287_direct.fastq.gz
    output: .tmp/cut_adapter_SE/HEK293T-WT1_run1_R1.fq.gz, internal_files/discarded_reads/HEK293T-WT1_run1_R1.tooshort.fq.gz, internal_files/discarded_reads/HEK293T-WT1_run1_R1.untrimmed.fq.gz, report_reads/trimming/HEK293T-WT1_run1.json
    jobid: 5
    reason: Missing output files: .tmp/cut_adapter_SE/HEK293T-WT1_run1_R1.fq.gz
    wildcards: sample=HEK293T-WT1, rn=run1
    threads: 20
    resources: tmpdir=/tmp

2024-10-23 14:12:26,189 -  WARNING - Library is not (-) strand, but --auto-rc is enabled. Ignored.
Done           00:02:33    90,057,645 reads @   1.7 µs/read;  35.30 M reads/minute
Traceback (most recent call last):
  File "/home/DDL/miniconda3/envs/snakemake/bin/cutseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 988, in main
    run_cutseq(args)
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 766, in run_cutseq
    pipeline_single(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 460, in pipeline_single
    json_report(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 299, in json_report
    d.update(stats.as_json())
             ^^^^^^^^^^^^^^^
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutadapt/report.py", line 240, in as_json
    self._adapter_statistics_as_json(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutadapt/report.py", line 301, in _adapter_statistics_as_json
    "error_lengths": make_line(eranges),
                     ^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

```

**Comment by y9c** [comment]
Thank you for the information. The first error might be due to an incomplete download of the data, while the second error could be caused by the CutSeq tool. Since CutSeq is still under active development, you can try the latest version.

**Comment by hengjwj** [comment]
Hi! I downloaded the latest version of Cutseq and re-ran again but got a similar error (changes in line numbers reported) regarding Cutseq:

```Traceback (most recent call last):
  File "/home/DDL/miniconda3/envs/snakemake/bin/cutseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 990, in main
    run_cutseq(args)
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 768, in run_cutseq
    pipeline_single(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 462, in pipeline_single
    json_report(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutseq/run.py", line 301, in json_report
    d.update(stats.as_json())
             ^^^^^^^^^^^^^^^
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutadapt/report.py", line 240, in as_json
    self._adapter_statistics_as_json(
  File "/home/DDL/miniconda3/envs/snakemake/lib/python3.12/site-packages/cutadapt/report.py", line 301, in _adapter_statistics_as_json
    "error_lengths": make_line(eranges),
                     ^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by y9c** [comment]
Could you show me your data?
